name: BukkitOpFixPlus
version: ${project.version}
description: fork of the BukkitOpFix by ZathrusWriter
author: [Ujun]
main: me.ujun.Main
api-version: '1.21'
commands:
  reload-bukkitopfix:
  setoplevel:
    permission: op
